tap "homebrew/bundle"
brew "awscli"
brew "gh"
brew "git"
brew "git-secrets"
brew "mas"
brew "mise"
brew "mysql"
brew "peco"
brew "tmux"
cask "1password"
cask "alfred"
cask "appcleaner"
cask "bettertouchtool"
cask "cleanshot"
cask "dash"
cask "deepl"
cask "docker"
cask "figma"
cask "google-chrome"
cask "google-japanese-ime"
cask "iterm2"
cask "jetbrains-toolbox"
cask "karabiner-elements"
cask "notion"
cask "popclip"
cask "postman"
cask "slack"
cask "sony-ps-remote-play"
cask "visual-studio-code"
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Kindle", id: 302584613
mas "Magnet", id: 441258766
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
vscode "ms-ceintl.vscode-language-pack-ja"
